import { JSXBase } from '@stencil/core/internal';
import React from 'react';
import { JSX as LocalJSX } from './components';

export { $tiToast } from './components/toast/toast';
export { $tiDialog } from './components/dialog/dialog';

/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
declare global {
  type StencilToReact<T> = {
    [P in keyof T]?: T[P] &
      Omit<React.HTMLAttributes<Element>, 'className'> & {
        class?: string;
      };
  };

  namespace JSX {
    type CustomIntrinsicElements = {
      [Tag in keyof LocalJSX.IntrinsicElements]: LocalJSX.IntrinsicElements[Tag] &
        JSXBase.HTMLAttributes<HTMLElementTagNameMap[Tag]>;
    };

    interface IntrinsicElements extends StencilToReact<CustomIntrinsicElements> {}
  }
}

export { Components, JSX } from './components';

export type { TimeGroup } from './components/countdown/index';
export { EDividerPosition, EDividerOrientation } from './components/divider/const';
export { initialize } from './global/global';
